#!/usr/bin/env ruby
# SPDX-License-Identifier: GPL-3.0-or-later
# Build dictionary-wide lookup aliases; no definitions or word-specific rules
# are embedded. Runtime still reads definitions from the active PredictEngine.
require 'json'
require 'fileutils'
require 'tempfile'

abort 'usage: build-zime-case-aliases.rb DECISIONS.tsv OUTPUT.inc' unless ARGV.length == 2
input, output = ARGV
aliases = File.foreach(input).each_with_object([]) do |line, rows|
  next if line.strip.empty? || line.start_with?('#')
  word, definition = line.chomp.split("\t", 2)
  abort 'invalid dictionary decision' unless word && definition && !word.empty?
  folded = word.tr('A-Z', 'a-z')
  rows << [folded, word] if definition != '-' && folded != word
end.uniq.sort
source = "// Generated by scripts/build-zime-case-aliases.rb; do not edit.\n"
source += "constexpr std::array<std::pair<std::string_view, std::string_view>, #{aliases.size}> kMetadataCaseAliases = {{\n"
aliases.each { |folded, word| source += "  {#{JSON.generate(folded)}, #{JSON.generate(word)}},\n" }
source += "}};\n"
unless File.file?(output) && File.binread(output) == source
  FileUtils.mkdir_p(File.dirname(output))
  Tempfile.create(['.zime-case-aliases-', '.inc'], File.dirname(output)) do |file|
    file.write(source)
    file.flush
    File.rename(file.path, output)
  end
end
puts "ZIME dictionary case aliases: #{aliases.size}"
